In [1]:
# Colab library to upload files to notebook
from google.colab import files

# Install Kaggle library
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.6/dist-packages (1.5.6)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.12.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from kaggle) (4.41.1)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.6/dist-packages (from kaggle) (4.0.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from kaggle) (2020.6.20)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.8.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.6/dist-packages (from python-slugify->kaggle) (1.3)

In [3]:
#Providing Kaggle API so that we can use Kaggle Dataset on Colab
import json
token = {"username":"neha49712","key":"e55a51446443d6c6c8938198a09f816c"}
with open('/content/kaggle.json', 'w') as file:
    json.dump(token, file)

In [12]:
# Copying My token to Kaggle root directory
!cp /content/kaggle.json ~/.kaggle/

In [13]:
# Setting Path for Route Directory
!kaggle config set -n path -v{/content}

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
- path is now set to: {/content}

In [14]:
#Removing Warning 
!chmod 600 /root/.kaggle/kaggle.json

In [15]:
#Checking lists of data avaiable on Kaggle
!kaggle datasets list

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.6 / client 1.5.4)
ref                                                           title                                                size  lastUpdated          downloadCount
------------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------
allen-institute-for-ai/CORD-19-research-challenge             COVID-19 Open Research Dataset Challenge (CORD-19)    4GB  2020-07-13 16:36:10          87914
roche-data-science-coalition/uncover                          UNCOVER COVID-19 Challenge                          179MB  2020-05-21 18:57:53          15390
oleksastepaniuk/prozorro-public-procurement-dataset           ProZorro. Ukrainian public procurement dataset      448MB  2020-04-15 17:09:37             45
navinmundhra/daily-power-generation-in-india-20172020         Daily Power Generation in India (2017-2020)          63KB  2020-06-29 17:13:29            500
mrmorj/data-police-shootings                                  Data Police shootings                               130KB  2020-06-17 18:19:37            992
rohanrao/chai-time-data-science                               Chai Time Data Science | CTDS.Show                    3MB  2020-06-20 23:01:09            229
nareshbhat/health-care-data-set-on-heart-attack-possibility   Health care: Data set on Heart attack possibility     3KB  2020-06-25 07:11:26           1172
mathchi/online-retail-data-set-from-ml-repository             Online Retail Data Set from ML Repository             1KB  2020-07-05 18:53:40            236
parulpandey/covid19-clinical-trials-dataset                   COVID-19 Clinical Trials dataset                     12MB  2020-07-09 10:02:47            282
miguelaenlle/massive-stock-news-analysis-db-for-nlpbacktests  Daily Financial News for 6000+ Stocks               210MB  2020-07-04 04:06:43            377
mathurinache/world-happiness-report                           World Happiness Report up to 2020                    54KB  2020-06-30 15:26:17           1288
imdevskp/cholera-dataset                                      Cholera Dataset                                      21KB  2020-07-01 17:28:18            316
imdevskp/malaria-dataset                                      Malaria Dataset                                      52KB  2020-07-01 17:28:22            486
dorianlazar/medium-articles-dataset                           Medium articles dataset                               1GB  2020-06-30 14:13:56            155
bahramjannesarr/goodreads-book-datasets-10m                   Goodreads Book Datasets With User Rating 10M        162MB  2020-07-12 14:49:43            244
benroshan/factors-affecting-campus-placement                  Campus Recruitment                                    5KB  2020-04-11 11:09:02          10913
bobbyscience/league-of-legends-diamond-ranked-games-10-min    League of Legends Diamond Ranked Games (10 min)     539KB  2020-04-13 13:53:02           4467
fireballbyedimyrnmom/us-counties-covid-19-dataset             US counties COVID 19 dataset                          3MB  2020-07-13 12:25:41           9896
divyansh22/flight-delay-prediction                            January Flight Delay Prediction                      23MB  2020-04-14 13:15:41           3714
clmentbisaillon/fake-and-real-news-dataset                    Fake and real news dataset                           41MB  2020-03-26 18:51:15           9399

In [16]:
# Downloading IMDB dataset from Kaggle on Colab
!kaggle datasets download -d arshid/iris-flower-dataset

Downloading iris-flower-dataset.zip to {/content}/datasets/arshid/iris-flower-dataset
  0% 0.00/0.99k [00:00<?, ?B/s]
100% 0.99k/0.99k [00:00<00:00, 1.88MB/s]

In [17]:
#Unzipping the data downloaded from Kaggle
!unzip /content/{/content}/datasets/arshid/iris-flower-dataset/iris-flower-dataset.zip

Archive:  /content/{/content}/datasets/arshid/iris-flower-dataset/iris-flower-dataset.zip
  inflating: IRIS.csv

In [18]:
#Importing pandas (Import statements should always be on top 
# this one is just to show where we are gonna use which library)
import pandas as pd

In [19]:
#Read csv file
iris_csv = pd.read_csv('/content/IRIS.csv')

In [20]:
#Let's describe our dataset
iris_csv.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [21]:
#It will show top 10 records of imdb dataset
iris_csv.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [22]:
# Spiliting the Dataset
x ,y = iris_csv.iloc[ : , :-1] ,iris_csv.iloc[: , -1]

In [23]:
x.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [24]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

In [25]:
#Spiliting Dataset
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [26]:
xTrain.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    120.000000   120.000000    120.000000   120.000000
mean       5.880833     3.053333      3.815833     1.230833
std        0.850437     0.431907      1.784904     0.776525
min        4.300000     2.000000      1.100000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.500000     3.300000      5.200000     1.900000
max        7.900000     4.400000      6.900000     2.500000

In [27]:
xTest.describe()

       sepal_length  sepal_width  petal_length  petal_width
count     30.000000    30.000000     30.000000    30.000000
mean       5.693333     3.056667      3.530000     1.070000
std        0.725370     0.447740      1.689552     0.704738
min        4.400000     2.200000      1.000000     0.100000
25%        5.000000     2.800000      1.525000     0.325000
50%        5.700000     2.900000      4.350000     1.250000
75%        6.175000     3.375000      4.700000     1.500000
max        7.300000     4.200000      6.300000     2.500000

In [28]:
yTrain.describe()

count                120
unique                 3
top       Iris-virginica
freq                  44
Name: species, dtype: object

In [29]:
yTest.describe()

count                  30
unique                  3
top       Iris-versicolor
freq                   13
Name: species, dtype: object

In [30]:
#Building Model
from sklearn import neighbors
classifier = neighbors.KNeighborsClassifier()

In [31]:
#Training the Model
classifier.fit(xTrain,yTrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [32]:
# Making prediction
predictions = classifier.predict(xTest)

In [33]:
# To check accuracy how good is your model
from sklearn.metrics import accuracy_score
print(accuracy_score(yTest,predictions))

0.9666666666666667

In [42]:
#Saving the model
import pickle
Saved_model  = pickle.dumps(classifier)

In [41]:
#Save model by another way
filename = 'MyModel.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [43]:
#load the model from disk
NewModel = pickle.load(open(filename, 'rb'))

In [38]:
#For checking Location of saved Model
import os
os.getcwd()

'/content'

In [44]:
#Checking Number of classes it can identify
NewModel.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [36]:
#Load the Pickle Model which was saved by First Method
Saved_model_pickle = pickle.loads(Saved_model)

In [37]:
#Testing the Loaded Model 
Saved_model_pickle.predict(xTest)

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)